### ISSUE TITLE
When launching "!r"

### ISSUE THREAD

**Issue by bigornoo** [giovannicoppola/alfred-readwise#4]
I've got this : 

```
[14:36:35.005] alfred-readwise[Script Filter] Queuing argument '(null)'
[14:36:35.187] alfred-readwise[Script Filter] Script with argv '(null)' finished
[14:36:35.188] ERROR: alfred-readwise[Script Filter] Code 1: 0 days from last update
Traceback (most recent call last):
  File "/Users/me/Library/CloudStorage/Dropbox/Applications/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8EF4C876-82A3-495C-ACF6-2A84D09A72F0/readwise-query.py", line 218, in <module>
    main ()
  File "/Users/me/Library/CloudStorage/Dropbox/Applications/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8EF4C876-82A3-495C-ACF6-2A84D09A72F0/readwise-query.py", line 213, in main
    queryItems (MY_DATABASE, MYINPUT)
  File "/Users/me/Library/CloudStorage/Dropbox/Applications/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8EF4C876-82A3-495C-ACF6-2A84D09A72F0/readwise-query.py", line 53, in queryItems
    tag_rows = db.execute(tag_statement).fetchall()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: tags
```
Thank you for your help

**Comment by giovannicoppola** [comment]
I had a [similar issue](https://github.com/giovannicoppola/alfred-readwise/issues/1) reported in the past, which turned out to be related to an invalid URL. If you are willing to do some troubleshooting, I can guide you, or if you want to send me the database I can find out for you.

**Comment by bigornoo** [comment]
Thank you for your help, but I'm a little short of time at the moment. Later :)
